name: submit predictions
on:
  schedule:
    - cron:  '3 * * * *'

jobs:
  get_new_games:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:

    - name: See event name
      run: |
        echo "title ${title}"
        echo "actor ${actor}"
        echo "event_name ${event_name}"
      env:
        title: ${{ github.event.issue.title }}
        actor: ${{ github.actor }}
        event_name: ${{ github.event_name }}

    - name: Copy Repository Contents
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: install dependencies
      run: |
        sudo apt-get update -y
        pip3 install numerox>=4.1.6

    - name: train model
      id: train_model
      run: |
        python3 ./train.py

    - name: submit predictions
      run: |
        python3 ./predict.py
